"""Topics, subtopics, lessons and seed questions for Trigonometry & Geometry."""

# Topic structure: parent topic -> list of subtopics
TOPICS_V2 = [
    {
        "id": "algebra", "name": "Algebra", "status": "available",
        "description": "Equations, inequalities, indices, logarithms, variation, sequences.",
        "icon": "Sigma",
    },
    {
        "id": "trigonometry", "name": "Trigonometry", "status": "available",
        "description": "Trig ratios, identities, sine & cosine rules, angles of elevation/depression, bearings.",
        "icon": "Triangle",
    },
    {
        "id": "geometry", "name": "Geometry", "status": "available",
        "description": "Circle theorems, polygons, area & volume, similarity, coordinate geometry.",
        "icon": "Shapes",
    },
    {"id": "statistics", "name": "Statistics", "status": "coming_soon", "description": "Mean, median, mode, standard deviation, probability.", "icon": "BarChart3"},
    {"id": "calculus",   "name": "Calculus",   "status": "coming_soon", "description": "Differentiation, integration, applications.", "icon": "TrendingUp"},
    {"id": "vectors",    "name": "Vectors",    "status": "coming_soon", "description": "Vector algebra and geometry.", "icon": "MoveUpRight"},
]

# Subtopics by topic
SUBTOPICS_BY_TOPIC = {
    "algebra": [
        {"id": "linear-equations", "name": "Linear Equations"},
        {"id": "quadratic-equations", "name": "Quadratic Equations"},
        {"id": "simultaneous-equations", "name": "Simultaneous Equations"},
        {"id": "indices", "name": "Indices"},
        {"id": "logarithms", "name": "Logarithms"},
        {"id": "variation", "name": "Variation"},
        {"id": "sequences-series", "name": "Sequences & Series"},
        {"id": "inequalities", "name": "Inequalities"},
    ],
    "trigonometry": [
        {"id": "trig-ratios", "name": "Trigonometric Ratios"},
        {"id": "trig-identities", "name": "Trigonometric Identities"},
        {"id": "sine-cosine-rules", "name": "Sine & Cosine Rules"},
        {"id": "elevation-depression", "name": "Angles of Elevation & Depression"},
        {"id": "bearings", "name": "Bearings"},
    ],
    "geometry": [
        {"id": "circle-theorems", "name": "Circle Theorems"},
        {"id": "polygons", "name": "Polygons"},
        {"id": "area-volume", "name": "Area & Volume"},
        {"id": "similarity-congruence", "name": "Similarity & Congruence"},
        {"id": "coordinate-geometry", "name": "Coordinate Geometry"},
    ],
}

# Lessons for Trigonometry & Geometry subtopics
LESSONS_V2 = {
    # ---- TRIGONOMETRY ----
    "trig-ratios": {
        "title": "Trigonometric Ratios", "topic": "trigonometry",
        "summary": "In a right-angled triangle, $\\sin\\theta = \\frac{opp}{hyp}$, $\\cos\\theta = \\frac{adj}{hyp}$, $\\tan\\theta = \\frac{opp}{adj}$.",
        "notes": [
            {"heading": "SOH-CAH-TOA",
             "body": "$\\sin\\theta = \\frac{\\text{opposite}}{\\text{hypotenuse}}$, $\\cos\\theta = \\frac{\\text{adjacent}}{\\text{hypotenuse}}$, $\\tan\\theta = \\frac{\\text{opposite}}{\\text{adjacent}}$."},
            {"heading": "Special Angles",
             "body": "Memorise: $\\sin 30°=\\frac{1}{2}$, $\\cos 30°=\\frac{\\sqrt{3}}{2}$, $\\tan 30°=\\frac{1}{\\sqrt{3}}$, $\\sin 60°=\\frac{\\sqrt{3}}{2}$, $\\sin 45°=\\cos 45°=\\frac{1}{\\sqrt{2}}$, $\\tan 45°=1$."},
            {"heading": "Worked Example",
             "body": "In a right triangle, the opposite side to angle $\\theta$ is 3 cm and hypotenuse is 5 cm. Find $\\sin\\theta$.\n\n$\\sin\\theta = \\frac{3}{5} = 0.6$."},
        ]
    },
    "trig-identities": {
        "title": "Trigonometric Identities", "topic": "trigonometry",
        "summary": "Key identity: $\\sin^2\\theta + \\cos^2\\theta = 1$.",
        "notes": [
            {"heading": "Fundamental Identities",
             "body": "$\\sin^2\\theta + \\cos^2\\theta = 1$; $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$; $1 + \\tan^2\\theta = \\sec^2\\theta$."},
            {"heading": "Worked Example",
             "body": "If $\\sin\\theta = \\frac{3}{5}$ and $\\theta$ is acute, find $\\cos\\theta$.\n\n$\\cos^2\\theta = 1 - \\frac{9}{25} = \\frac{16}{25}$, so $\\cos\\theta = \\frac{4}{5}$."},
        ]
    },
    "sine-cosine-rules": {
        "title": "Sine & Cosine Rules", "topic": "trigonometry",
        "summary": "For any triangle ABC, $\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}$ and $a^2 = b^2 + c^2 - 2bc\\cos A$.",
        "notes": [
            {"heading": "Sine Rule",
             "body": "$$\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}$$ Use when given two angles and any side, or two sides and a non-included angle."},
            {"heading": "Cosine Rule",
             "body": "$$a^2 = b^2 + c^2 - 2bc\\cos A$$ Use when given three sides, or two sides and the included angle."},
            {"heading": "Worked Example",
             "body": "In $\\triangle ABC$, $b = 8$, $c = 10$, $A = 60°$. Find $a$.\n\nBy cosine rule: $a^2 = 64 + 100 - 2(8)(10)(0.5) = 164 - 80 = 84$, so $a = \\sqrt{84} \\approx 9.17$."},
        ]
    },
    "elevation-depression": {
        "title": "Angles of Elevation & Depression", "topic": "trigonometry",
        "summary": "Used to solve real-world height & distance problems.",
        "notes": [
            {"heading": "Definitions",
             "body": "**Elevation**: angle from the horizontal up to an object above the observer. **Depression**: angle from the horizontal down to an object below."},
            {"heading": "Worked Example",
             "body": "From a point 50 m from the foot of a tower, the angle of elevation to the top is $30°$. Find the tower's height.\n\n$\\tan 30° = \\frac{h}{50} \\Rightarrow h = 50 \\times \\frac{1}{\\sqrt{3}} = \\frac{50}{\\sqrt{3}} \\approx 28.87$ m."},
        ]
    },
    "bearings": {
        "title": "Bearings", "topic": "trigonometry",
        "summary": "Compass bearings are measured clockwise from north as a three-digit angle.",
        "notes": [
            {"heading": "Notation",
             "body": "Bearings are always written with 3 digits, e.g. due East = $090°$, due South = $180°$. Conventional 'N $\\theta°$ E' is sometimes used too."},
            {"heading": "Worked Example",
             "body": "A ship sails on a bearing of $060°$ for 8 km. How far east has it travelled?\n\nEast distance $= 8\\sin 60° = 8 \\times \\frac{\\sqrt{3}}{2} \\approx 6.93$ km."},
        ]
    },

    # ---- GEOMETRY ----
    "circle-theorems": {
        "title": "Circle Theorems", "topic": "geometry",
        "summary": "Properties of angles, chords, and tangents in a circle.",
        "notes": [
            {"heading": "Key Theorems",
             "body": "1) Angle at centre = $2\\times$ angle at circumference on the same arc. 2) Angles in the same segment are equal. 3) Angle in a semicircle = $90°$. 4) Opposite angles in a cyclic quadrilateral sum to $180°$. 5) Tangent ⊥ radius at the point of contact."},
            {"heading": "Worked Example",
             "body": "If the angle at the centre of a circle is $80°$, the angle at the circumference on the same arc is $\\frac{80°}{2} = 40°$."},
        ]
    },
    "polygons": {
        "title": "Polygons", "topic": "geometry",
        "summary": "Sum of interior angles $= (n - 2) \\times 180°$; sum of exterior angles $= 360°$.",
        "notes": [
            {"heading": "Angle Sums",
             "body": "Interior: $(n-2)\\times 180°$. Each interior of a regular n-gon: $\\frac{(n-2)\\times 180°}{n}$. Exterior of a regular n-gon: $\\frac{360°}{n}$."},
            {"heading": "Worked Example",
             "body": "Find each interior angle of a regular hexagon.\n\n$\\frac{(6-2)\\times 180°}{6} = \\frac{720°}{6} = 120°$."},
        ]
    },
    "area-volume": {
        "title": "Area & Volume", "topic": "geometry",
        "summary": "Formulas for plane areas and 3D volumes.",
        "notes": [
            {"heading": "Common Formulas",
             "body": "Area of circle $=\\pi r^2$; circumference $=2\\pi r$. Sphere volume $=\\frac{4}{3}\\pi r^3$. Cylinder $=\\pi r^2 h$. Cone $=\\frac{1}{3}\\pi r^2 h$. Triangle $=\\frac{1}{2}\\times base \\times height$."},
            {"heading": "Worked Example",
             "body": "Find the volume of a cylinder with $r = 7$ cm and $h = 10$ cm. Take $\\pi = \\frac{22}{7}$.\n\n$V = \\frac{22}{7} \\times 49 \\times 10 = 1540$ cm³."},
        ]
    },
    "similarity-congruence": {
        "title": "Similarity & Congruence", "topic": "geometry",
        "summary": "Similar triangles have equal corresponding angles and proportional sides.",
        "notes": [
            {"heading": "Tests",
             "body": "**Congruence**: SSS, SAS, ASA, RHS. **Similarity**: AAA (equal angles) or sides in equal ratio. If ratio of sides $= k$, ratio of areas $= k^2$, ratio of volumes $= k^3$."},
            {"heading": "Worked Example",
             "body": "Two similar triangles have areas in ratio $9:16$. Find the ratio of corresponding sides.\n\nRatio of sides $= \\sqrt{9}:\\sqrt{16} = 3:4$."},
        ]
    },
    "coordinate-geometry": {
        "title": "Coordinate Geometry", "topic": "geometry",
        "summary": "Working with points, lines, distances and gradients on the Cartesian plane.",
        "notes": [
            {"heading": "Key Formulas",
             "body": "Distance: $d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$. Midpoint: $\\left(\\frac{x_1+x_2}{2},\\frac{y_1+y_2}{2}\\right)$. Gradient: $m = \\frac{y_2 - y_1}{x_2 - x_1}$. Line: $y - y_1 = m(x - x_1)$."},
            {"heading": "Worked Example",
             "body": "Find the distance between $(2, 3)$ and $(7, 15)$.\n\n$d = \\sqrt{(7-2)^2 + (15-3)^2} = \\sqrt{25 + 144} = \\sqrt{169} = 13$."},
        ]
    },
}

# Seed questions for Trigonometry & Geometry (25 + 25)
QUESTIONS_V2 = [
    # ---- TRIGONOMETRY ----
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2018, "difficulty": "easy",
     "question": "If $\\sin\\theta = \\frac{3}{5}$, find $\\tan\\theta$ ($\\theta$ acute).",
     "options": ["$\\frac{3}{4}$", "$\\frac{4}{3}$", "$\\frac{4}{5}$", "$\\frac{5}{3}$"], "answer": "$\\frac{3}{4}$",
     "solution_steps": ["$\\cos\\theta = \\sqrt{1 - \\frac{9}{25}} = \\frac{4}{5}$.", "$\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta} = \\frac{3/5}{4/5} = \\frac{3}{4}$."]},
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2020, "difficulty": "easy",
     "question": "Find the value of $\\sin 30° + \\cos 60°$.",
     "options": ["$0$", "$\\frac{1}{2}$", "$1$", "$\\sqrt{3}$"], "answer": "$1$",
     "solution_steps": ["$\\sin 30° = \\frac{1}{2}$ and $\\cos 60° = \\frac{1}{2}$.", "Sum $= 1$."]},
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2019, "difficulty": "medium",
     "question": "In a right triangle, opposite = 7 cm, adjacent = 24 cm. Find the hypotenuse.",
     "options": ["23 cm", "25 cm", "26 cm", "28 cm"], "answer": "25 cm",
     "solution_steps": ["By Pythagoras: $h = \\sqrt{7^2 + 24^2} = \\sqrt{49 + 576} = \\sqrt{625} = 25$ cm."]},
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2022, "difficulty": "hard",
     "question": "If $\\tan\\theta = \\frac{5}{12}$, find $\\sin\\theta + \\cos\\theta$.",
     "options": ["$\\frac{17}{13}$", "$\\frac{12}{13}$", "$\\frac{5}{13}$", "$\\frac{7}{13}$"], "answer": "$\\frac{17}{13}$",
     "solution_steps": ["Opp = 5, Adj = 12, Hyp $=\\sqrt{169}=13$.", "$\\sin\\theta = \\frac{5}{13}$, $\\cos\\theta=\\frac{12}{13}$.", "Sum $= \\frac{17}{13}$."]},
    {"topic": "trigonometry", "subtopic": "trig-identities", "year": 2021, "difficulty": "medium",
     "question": "Simplify: $\\sin^2 30° + \\cos^2 30°$.",
     "options": ["0", "1", "$\\frac{1}{2}$", "2"], "answer": "1",
     "solution_steps": ["By identity $\\sin^2\\theta + \\cos^2\\theta = 1$ for any $\\theta$.", "Answer = 1."]},
    {"topic": "trigonometry", "subtopic": "trig-identities", "year": 2017, "difficulty": "hard",
     "question": "If $\\cos\\theta = \\frac{8}{17}$ and $\\theta$ is acute, find $\\sin\\theta$.",
     "options": ["$\\frac{15}{17}$", "$\\frac{8}{15}$", "$\\frac{17}{15}$", "$\\frac{15}{8}$"], "answer": "$\\frac{15}{17}$",
     "solution_steps": ["$\\sin^2\\theta = 1 - \\frac{64}{289} = \\frac{225}{289}$.", "$\\sin\\theta = \\frac{15}{17}$."]},
    {"topic": "trigonometry", "subtopic": "sine-cosine-rules", "year": 2020, "difficulty": "medium",
     "question": "In $\\triangle ABC$, $a = 7$, $b = 8$, $C = 60°$. Find $c$ to 2 d.p.",
     "options": ["7.55", "8.66", "7.81", "9.00"], "answer": "7.55",
     "solution_steps": ["Cosine rule: $c^2 = 49 + 64 - 2(7)(8)(0.5) = 113 - 56 = 57$.", "$c = \\sqrt{57} \\approx 7.55$."]},
    {"topic": "trigonometry", "subtopic": "sine-cosine-rules", "year": 2019, "difficulty": "medium",
     "question": "In $\\triangle PQR$, $\\angle P = 40°$, $\\angle Q = 60°$, $p = 6$. Find $q$ to 2 d.p.",
     "options": ["8.08", "7.21", "5.18", "9.12"], "answer": "8.08",
     "solution_steps": ["Sine rule: $\\frac{6}{\\sin 40°} = \\frac{q}{\\sin 60°}$.", "$q = \\frac{6\\sin 60°}{\\sin 40°} = \\frac{6 \\times 0.866}{0.643} \\approx 8.08$."]},
    {"topic": "trigonometry", "subtopic": "sine-cosine-rules", "year": 2023, "difficulty": "hard",
     "question": "A triangle has sides 5, 7, 8. Find the largest angle to nearest degree.",
     "options": ["60°", "75°", "82°", "90°"], "answer": "82°",
     "solution_steps": ["Largest angle opposite longest side (8).", "$\\cos C = \\frac{5^2 + 7^2 - 8^2}{2(5)(7)} = \\frac{10}{70} = 0.1429$.", "$C \\approx 81.79° \\approx 82°$."]},
    {"topic": "trigonometry", "subtopic": "elevation-depression", "year": 2018, "difficulty": "medium",
     "question": "A pole casts a 12 m shadow when the sun's elevation is $30°$. Find the pole height.",
     "options": ["6.0 m", "6.93 m", "8.0 m", "10.4 m"], "answer": "6.93 m",
     "solution_steps": ["$\\tan 30° = \\frac{h}{12}$.", "$h = 12 \\times \\frac{1}{\\sqrt{3}} \\approx 6.93$ m."]},
    {"topic": "trigonometry", "subtopic": "elevation-depression", "year": 2021, "difficulty": "hard",
     "question": "From a cliff 100 m above the sea, the angle of depression of a boat is $45°$. Find horizontal distance.",
     "options": ["50 m", "100 m", "141 m", "200 m"], "answer": "100 m",
     "solution_steps": ["$\\tan 45° = \\frac{100}{d} = 1$.", "Therefore $d = 100$ m."]},
    {"topic": "trigonometry", "subtopic": "elevation-depression", "year": 2022, "difficulty": "easy",
     "question": "An observer at height 0 sees a balloon at $60°$ elevation, 50 m away horizontally. Find the balloon's height.",
     "options": ["43.3 m", "50 m", "86.6 m", "100 m"], "answer": "86.6 m",
     "solution_steps": ["$\\tan 60° = \\frac{h}{50}$.", "$h = 50\\sqrt{3} \\approx 86.6$ m."]},
    {"topic": "trigonometry", "subtopic": "bearings", "year": 2019, "difficulty": "medium",
     "question": "A ship sails 10 km on bearing $090°$, then 10 km on bearing $180°$. How far is it from the start?",
     "options": ["10 km", "14.14 km", "20 km", "15 km"], "answer": "14.14 km",
     "solution_steps": ["The journey forms an L-shape. East = 10 km, South = 10 km.", "Distance $= \\sqrt{100 + 100} = 10\\sqrt{2} \\approx 14.14$ km."]},
    {"topic": "trigonometry", "subtopic": "bearings", "year": 2020, "difficulty": "hard",
     "question": "A boat sails from A on bearing $060°$ to B, 12 km away. What is the east displacement?",
     "options": ["6 km", "10.39 km", "12 km", "8 km"], "answer": "10.39 km",
     "solution_steps": ["East $= 12\\sin 60° = 12 \\times \\frac{\\sqrt{3}}{2} \\approx 10.39$ km."]},
    {"topic": "trigonometry", "subtopic": "bearings", "year": 2017, "difficulty": "easy",
     "question": "What is the bearing of due West?",
     "options": ["090°", "180°", "270°", "000°"], "answer": "270°",
     "solution_steps": ["Bearings are measured clockwise from north.", "Due West $= 270°$."]},
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2023, "difficulty": "easy",
     "question": "$\\tan 45°$ equals:",
     "options": ["0", "1", "$\\frac{1}{\\sqrt{2}}$", "$\\sqrt{3}$"], "answer": "1",
     "solution_steps": ["By special angle, $\\tan 45° = 1$."]},
    {"topic": "trigonometry", "subtopic": "trig-identities", "year": 2023, "difficulty": "medium",
     "question": "If $\\sin\\theta = \\cos\\theta$, find $\\theta$ in the range $0° \\leq \\theta \\leq 90°$.",
     "options": ["0°", "30°", "45°", "60°"], "answer": "45°",
     "solution_steps": ["$\\sin\\theta = \\cos\\theta \\Rightarrow \\tan\\theta = 1$.", "$\\theta = 45°$."]},
    {"topic": "trigonometry", "subtopic": "sine-cosine-rules", "year": 2018, "difficulty": "hard",
     "question": "In $\\triangle ABC$, $a = 9$, $b = 12$, $\\angle A = 30°$. Find $\\sin B$.",
     "options": ["$\\frac{1}{3}$", "$\\frac{2}{3}$", "$\\frac{1}{2}$", "$\\frac{3}{4}$"], "answer": "$\\frac{2}{3}$",
     "solution_steps": ["Sine rule: $\\frac{9}{\\sin 30°} = \\frac{12}{\\sin B}$.", "$\\sin B = \\frac{12 \\times 0.5}{9} = \\frac{6}{9} = \\frac{2}{3}$."]},
    {"topic": "trigonometry", "subtopic": "elevation-depression", "year": 2023, "difficulty": "medium",
     "question": "From a building 30 m tall, the angle of depression to a car is $30°$. How far is the car?",
     "options": ["30 m", "17.32 m", "51.96 m", "60 m"], "answer": "51.96 m",
     "solution_steps": ["$\\tan 30° = \\frac{30}{d}$.", "$d = \\frac{30}{\\tan 30°} = 30\\sqrt{3} \\approx 51.96$ m."]},
    {"topic": "trigonometry", "subtopic": "bearings", "year": 2022, "difficulty": "medium",
     "question": "If A is north of B, what is the bearing of B from A?",
     "options": ["000°", "090°", "180°", "270°"], "answer": "180°",
     "solution_steps": ["If A is north of B, then B is south of A.", "Bearing of B from A = $180°$."]},
    {"topic": "trigonometry", "subtopic": "trig-ratios", "year": 2017, "difficulty": "medium",
     "question": "Evaluate $2\\sin 30° \\cos 60°$.",
     "options": ["$\\frac{1}{4}$", "$\\frac{1}{2}$", "$1$", "$\\frac{\\sqrt{3}}{2}$"], "answer": "$\\frac{1}{2}$",
     "solution_steps": ["$\\sin 30° = \\frac{1}{2}$, $\\cos 60° = \\frac{1}{2}$.", "$2 \\times \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{2}$."]},
    {"topic": "trigonometry", "subtopic": "trig-identities", "year": 2016, "difficulty": "hard",
     "question": "Simplify: $\\frac{1 - \\cos^2\\theta}{\\sin\\theta}$.",
     "options": ["$\\sin\\theta$", "$\\cos\\theta$", "$\\tan\\theta$", "$1$"], "answer": "$\\sin\\theta$",
     "solution_steps": ["$1 - \\cos^2\\theta = \\sin^2\\theta$.", "$\\frac{\\sin^2\\theta}{\\sin\\theta} = \\sin\\theta$."]},
    {"topic": "trigonometry", "subtopic": "sine-cosine-rules", "year": 2016, "difficulty": "easy",
     "question": "In $\\triangle ABC$, if $A = 90°$, $b = 3$, $c = 4$, find $a$.",
     "options": ["5", "6", "7", "$\\sqrt{7}$"], "answer": "5",
     "solution_steps": ["By Pythagoras (special case of cosine rule when $A=90°$): $a^2 = 9 + 16 = 25$.", "$a = 5$."]},
    {"topic": "trigonometry", "subtopic": "elevation-depression", "year": 2016, "difficulty": "hard",
     "question": "A ladder leans against a wall, foot 5 m from wall, top reaches 12 m up. Find elevation of ladder.",
     "options": ["$\\tan^{-1}(\\frac{12}{5})$", "$\\tan^{-1}(\\frac{5}{12})$", "$\\sin^{-1}(\\frac{5}{12})$", "$60°$"], "answer": "$\\tan^{-1}(\\frac{12}{5})$",
     "solution_steps": ["$\\tan\\theta = \\frac{opp}{adj} = \\frac{12}{5}$.", "$\\theta = \\tan^{-1}\\left(\\frac{12}{5}\\right) \\approx 67.38°$."]},
    {"topic": "trigonometry", "subtopic": "bearings", "year": 2016, "difficulty": "medium",
     "question": "A plane flies on bearing $135°$. The north component of its velocity is negative. (T/F)",
     "options": ["True", "False", "Cannot tell", "Zero"], "answer": "True",
     "solution_steps": ["Bearing $135°$ is in the south-east direction.", "The northward (y) component is $\\cos 135° < 0$, so the north component is negative — True."]},

    # ---- GEOMETRY ----
    {"topic": "geometry", "subtopic": "circle-theorems", "year": 2018, "difficulty": "easy",
     "question": "The angle at the centre of a circle is $120°$. Find the angle at the circumference on the same arc.",
     "options": ["30°", "60°", "120°", "240°"], "answer": "60°",
     "solution_steps": ["Angle at centre $= 2 \\times$ angle at circumference.", "Angle at circumference $= \\frac{120°}{2} = 60°$."]},
    {"topic": "geometry", "subtopic": "circle-theorems", "year": 2020, "difficulty": "medium",
     "question": "In a cyclic quadrilateral, one angle is $70°$. Find the opposite angle.",
     "options": ["20°", "70°", "110°", "180°"], "answer": "110°",
     "solution_steps": ["Opposite angles in cyclic quadrilateral sum to $180°$.", "Opposite = $180° - 70° = 110°$."]},
    {"topic": "geometry", "subtopic": "circle-theorems", "year": 2019, "difficulty": "hard",
     "question": "$AB$ is a diameter and $C$ is on the circle. Find $\\angle ACB$.",
     "options": ["45°", "60°", "90°", "180°"], "answer": "90°",
     "solution_steps": ["Angle in a semicircle is always $90°$.", "Therefore $\\angle ACB = 90°$."]},
    {"topic": "geometry", "subtopic": "polygons", "year": 2017, "difficulty": "easy",
     "question": "Find the sum of interior angles of a pentagon.",
     "options": ["360°", "540°", "720°", "900°"], "answer": "540°",
     "solution_steps": ["$(n-2)\\times 180° = (5-2)\\times 180° = 540°$."]},
    {"topic": "geometry", "subtopic": "polygons", "year": 2021, "difficulty": "medium",
     "question": "Each interior angle of a regular polygon is $144°$. Find the number of sides.",
     "options": ["8", "9", "10", "12"], "answer": "10",
     "solution_steps": ["Each exterior $= 180° - 144° = 36°$.", "Number of sides $= \\frac{360°}{36°} = 10$."]},
    {"topic": "geometry", "subtopic": "polygons", "year": 2022, "difficulty": "hard",
     "question": "The exterior angles of a regular polygon sum to $360°$ and each is $20°$. Find the interior angle.",
     "options": ["140°", "150°", "160°", "170°"], "answer": "160°",
     "solution_steps": ["Each interior $+$ each exterior $= 180°$.", "Interior $= 180° - 20° = 160°$."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2018, "difficulty": "easy",
     "question": "Find the area of a circle with radius 7 cm. (Take $\\pi = \\frac{22}{7}$.)",
     "options": ["44 cm²", "77 cm²", "154 cm²", "308 cm²"], "answer": "154 cm²",
     "solution_steps": ["$A = \\pi r^2 = \\frac{22}{7} \\times 49 = 154$ cm²."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2020, "difficulty": "medium",
     "question": "Find the volume of a cone with $r = 3$ cm, $h = 7$ cm. (Take $\\pi = \\frac{22}{7}$.)",
     "options": ["22 cm³", "44 cm³", "66 cm³", "88 cm³"], "answer": "66 cm³",
     "solution_steps": ["$V = \\frac{1}{3}\\pi r^2 h = \\frac{1}{3} \\times \\frac{22}{7} \\times 9 \\times 7 = 66$ cm³."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2019, "difficulty": "hard",
     "question": "A sphere has radius 6 cm. Find its surface area to nearest whole. (Take $\\pi = 3.14$.)",
     "options": ["113", "452", "302", "904"], "answer": "452",
     "solution_steps": ["$A = 4\\pi r^2 = 4 \\times 3.14 \\times 36 = 452.16$.", "Nearest whole = 452 cm²."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2023, "difficulty": "medium",
     "question": "Find the area of a triangle with base 12 cm and height 9 cm.",
     "options": ["54 cm²", "72 cm²", "108 cm²", "21 cm²"], "answer": "54 cm²",
     "solution_steps": ["$A = \\frac{1}{2} \\times 12 \\times 9 = 54$ cm²."]},
    {"topic": "geometry", "subtopic": "similarity-congruence", "year": 2017, "difficulty": "medium",
     "question": "Two similar rectangles have sides in ratio $2:5$. Find the ratio of their areas.",
     "options": ["2:5", "4:10", "4:25", "8:125"], "answer": "4:25",
     "solution_steps": ["Ratio of areas $= (\\text{side ratio})^2 = 2^2 : 5^2 = 4 : 25$."]},
    {"topic": "geometry", "subtopic": "similarity-congruence", "year": 2021, "difficulty": "easy",
     "question": "Two triangles are similar; corresponding sides are 3 cm and 9 cm. What is the scale factor?",
     "options": ["1", "2", "3", "9"], "answer": "3",
     "solution_steps": ["Scale factor $= \\frac{9}{3} = 3$."]},
    {"topic": "geometry", "subtopic": "similarity-congruence", "year": 2022, "difficulty": "hard",
     "question": "Two similar cones have heights $4$ cm and $12$ cm. Find ratio of their volumes.",
     "options": ["1:3", "1:9", "1:27", "1:81"], "answer": "1:27",
     "solution_steps": ["Ratio of heights $= 1:3$.", "Ratio of volumes $= 1^3 : 3^3 = 1:27$."]},
    {"topic": "geometry", "subtopic": "coordinate-geometry", "year": 2018, "difficulty": "easy",
     "question": "Find the distance between $(0, 0)$ and $(6, 8)$.",
     "options": ["10", "14", "$\\sqrt{14}$", "12"], "answer": "10",
     "solution_steps": ["$d = \\sqrt{36 + 64} = \\sqrt{100} = 10$."]},
    {"topic": "geometry", "subtopic": "coordinate-geometry", "year": 2020, "difficulty": "medium",
     "question": "Find the midpoint of $(2, -3)$ and $(8, 5)$.",
     "options": ["(5, 1)", "(10, 2)", "(3, 4)", "(5, -1)"], "answer": "(5, 1)",
     "solution_steps": ["Midpoint $= \\left(\\frac{2+8}{2}, \\frac{-3+5}{2}\\right) = (5, 1)$."]},
    {"topic": "geometry", "subtopic": "coordinate-geometry", "year": 2019, "difficulty": "medium",
     "question": "Find the gradient of the line through $(1, 2)$ and $(4, 11)$.",
     "options": ["$3$", "$\\frac{1}{3}$", "$\\frac{9}{5}$", "$-3$"], "answer": "$3$",
     "solution_steps": ["$m = \\frac{11 - 2}{4 - 1} = \\frac{9}{3} = 3$."]},
    {"topic": "geometry", "subtopic": "coordinate-geometry", "year": 2021, "difficulty": "hard",
     "question": "Find the equation of the line with gradient 2 passing through $(3, 1)$.",
     "options": ["$y = 2x - 5$", "$y = 2x + 5$", "$y = 2x + 1$", "$y = -2x + 5$"], "answer": "$y = 2x - 5$",
     "solution_steps": ["Using $y - y_1 = m(x - x_1)$: $y - 1 = 2(x - 3)$.", "$y = 2x - 6 + 1 = 2x - 5$."]},
    {"topic": "geometry", "subtopic": "circle-theorems", "year": 2023, "difficulty": "medium",
     "question": "Two chords of a circle are equidistant from the centre. What is true about them?",
     "options": ["They are perpendicular", "They are equal in length", "One is a diameter", "They are parallel"], "answer": "They are equal in length",
     "solution_steps": ["Theorem: chords equidistant from the centre of a circle are equal in length."]},
    {"topic": "geometry", "subtopic": "polygons", "year": 2023, "difficulty": "easy",
     "question": "What is the size of each interior angle of a regular octagon?",
     "options": ["108°", "120°", "135°", "144°"], "answer": "135°",
     "solution_steps": ["Sum of interior $=(8-2)\\times 180° = 1080°$.", "Each $= \\frac{1080°}{8} = 135°$."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2017, "difficulty": "hard",
     "question": "Find the volume of a cylinder with $r = 5$ cm, $h = 10$ cm (use $\\pi = 3.14$).",
     "options": ["157", "314", "628", "785"], "answer": "785",
     "solution_steps": ["$V = \\pi r^2 h = 3.14 \\times 25 \\times 10 = 785$ cm³."]},
    {"topic": "geometry", "subtopic": "similarity-congruence", "year": 2018, "difficulty": "medium",
     "question": "A photograph 4 cm × 6 cm is enlarged so its width becomes 12 cm. Find the new length.",
     "options": ["12 cm", "16 cm", "18 cm", "24 cm"], "answer": "18 cm",
     "solution_steps": ["Scale factor $= \\frac{12}{4} = 3$.", "New length $= 6 \\times 3 = 18$ cm."]},
    {"topic": "geometry", "subtopic": "coordinate-geometry", "year": 2022, "difficulty": "easy",
     "question": "The point $(3, -2)$ lies in which quadrant?",
     "options": ["First", "Second", "Third", "Fourth"], "answer": "Fourth",
     "solution_steps": ["Positive $x$, negative $y$ → fourth quadrant."]},
    {"topic": "geometry", "subtopic": "circle-theorems", "year": 2016, "difficulty": "hard",
     "question": "A tangent meets a radius at the point of contact. What is the angle between them?",
     "options": ["45°", "60°", "90°", "180°"], "answer": "90°",
     "solution_steps": ["The tangent to a circle is perpendicular to the radius at the point of contact.", "Angle = $90°$."]},
    {"topic": "geometry", "subtopic": "polygons", "year": 2016, "difficulty": "medium",
     "question": "An interior angle of a regular polygon is $156°$. How many sides has it?",
     "options": ["12", "15", "18", "20"], "answer": "15",
     "solution_steps": ["Exterior $= 180° - 156° = 24°$.", "Sides $= \\frac{360°}{24°} = 15$."]},
    {"topic": "geometry", "subtopic": "area-volume", "year": 2016, "difficulty": "easy",
     "question": "Find the circumference of a circle with diameter 14 cm. (Take $\\pi = \\frac{22}{7}$.)",
     "options": ["22 cm", "44 cm", "88 cm", "154 cm"], "answer": "44 cm",
     "solution_steps": ["$C = \\pi d = \\frac{22}{7} \\times 14 = 44$ cm."]},
]

# 30 more algebra questions spanning 2010–2024 to expand the past-paper coverage.
ALGEBRA_EXTRA_QUESTIONS = [
    {"topic": "algebra", "subtopic": "linear-equations", "year": 2010, "difficulty": "easy",
     "question": "Solve: $x + 8 = 15$.", "options": ["5", "6", "7", "8"], "answer": "7",
     "solution_steps": ["Subtract 8: $x = 15 - 8 = 7$."]},
    {"topic": "algebra", "subtopic": "linear-equations", "year": 2011, "difficulty": "easy",
     "question": "Solve: $4x = 28$.", "options": ["5", "6", "7", "8"], "answer": "7",
     "solution_steps": ["Divide by 4: $x = 7$."]},
    {"topic": "algebra", "subtopic": "linear-equations", "year": 2012, "difficulty": "medium",
     "question": "If $\\frac{x}{2} + 3 = 7$, find $x$.", "options": ["4", "6", "8", "10"], "answer": "8",
     "solution_steps": ["$\\frac{x}{2} = 4$.", "$x = 8$."]},
    {"topic": "algebra", "subtopic": "quadratic-equations", "year": 2010, "difficulty": "medium",
     "question": "Solve $x^2 = 49$.", "options": ["7", "$\\pm 7$", "−7", "14"], "answer": "$\\pm 7$",
     "solution_steps": ["Take square root: $x = \\pm 7$."]},
    {"topic": "algebra", "subtopic": "quadratic-equations", "year": 2013, "difficulty": "medium",
     "question": "Factor $x^2 + 5x + 6$.", "options": ["$(x+2)(x+3)$", "$(x+1)(x+6)$", "$(x-2)(x-3)$", "$(x+5)(x+6)$"], "answer": "$(x+2)(x+3)$",
     "solution_steps": ["Find numbers multiplying to 6, adding to 5: 2 and 3.", "$(x+2)(x+3)$."]},
    {"topic": "algebra", "subtopic": "quadratic-equations", "year": 2011, "difficulty": "hard",
     "question": "Solve: $2x^2 - 8 = 0$.", "options": ["$\\pm 2$", "$\\pm 4$", "$\\pm\\sqrt{2}$", "$2$"], "answer": "$\\pm 2$",
     "solution_steps": ["$2x^2 = 8$, so $x^2 = 4$.", "$x = \\pm 2$."]},
    {"topic": "algebra", "subtopic": "indices", "year": 2012, "difficulty": "easy",
     "question": "Simplify $a^3 \\cdot a^2$.", "options": ["$a^5$", "$a^6$", "$2a^5$", "$a$"], "answer": "$a^5$",
     "solution_steps": ["Add powers: $a^{3+2}=a^5$."]},
    {"topic": "algebra", "subtopic": "indices", "year": 2014, "difficulty": "medium",
     "question": "Evaluate $16^{0.5}$.", "options": ["2", "4", "8", "16"], "answer": "4",
     "solution_steps": ["$16^{1/2} = \\sqrt{16} = 4$."]},
    {"topic": "algebra", "subtopic": "indices", "year": 2015, "difficulty": "hard",
     "question": "If $3^x = 81$, find $x$.", "options": ["3", "4", "5", "9"], "answer": "4",
     "solution_steps": ["$81 = 3^4$, so $x = 4$."]},
    {"topic": "algebra", "subtopic": "logarithms", "year": 2010, "difficulty": "easy",
     "question": "$\\log_{10} 100$ equals:", "options": ["1", "2", "10", "100"], "answer": "2",
     "solution_steps": ["$100 = 10^2$, so $\\log_{10}100 = 2$."]},
    {"topic": "algebra", "subtopic": "logarithms", "year": 2013, "difficulty": "medium",
     "question": "Simplify $\\log 4 + \\log 25$ (base 10).", "options": ["$\\log 9$", "$\\log 29$", "$\\log 100$", "$\\log 100 = 2$"], "answer": "$\\log 100 = 2$",
     "solution_steps": ["$\\log 4 + \\log 25 = \\log(4 \\times 25) = \\log 100 = 2$."]},
    {"topic": "algebra", "subtopic": "logarithms", "year": 2015, "difficulty": "hard",
     "question": "If $\\log_3 x = 2$, find $x$.", "options": ["3", "6", "9", "27"], "answer": "9",
     "solution_steps": ["$x = 3^2 = 9$."]},
    {"topic": "algebra", "subtopic": "simultaneous-equations", "year": 2010, "difficulty": "medium",
     "question": "Solve: $x + y = 6$, $x - y = 2$.", "options": ["(4, 2)", "(2, 4)", "(3, 3)", "(5, 1)"], "answer": "(4, 2)",
     "solution_steps": ["Add: $2x = 8 \\Rightarrow x = 4$.", "$4 - y = 2 \\Rightarrow y = 2$."]},
    {"topic": "algebra", "subtopic": "simultaneous-equations", "year": 2013, "difficulty": "medium",
     "question": "Solve: $2x + y = 8$, $x + y = 5$.", "options": ["(3, 2)", "(2, 3)", "(4, 1)", "(1, 4)"], "answer": "(3, 2)",
     "solution_steps": ["Subtract: $x = 3$.", "$3 + y = 5 \\Rightarrow y = 2$."]},
    {"topic": "algebra", "subtopic": "simultaneous-equations", "year": 2014, "difficulty": "hard",
     "question": "Solve: $3x - y = 5$, $x + 2y = 11$.", "options": ["(3, 4)", "(2, 3)", "(4, 7)", "(1, 5)"], "answer": "(3, 4)",
     "solution_steps": ["From eq1: $y = 3x - 5$.", "Sub into eq2: $x + 2(3x-5) = 11 \\Rightarrow 7x = 21 \\Rightarrow x = 3$.", "$y = 3(3) - 5 = 4$."]},
    {"topic": "algebra", "subtopic": "variation", "year": 2011, "difficulty": "easy",
     "question": "$y$ varies directly as $x$. $y = 6$ when $x = 2$. Find $y$ when $x = 5$.",
     "options": ["10", "12", "15", "18"], "answer": "15",
     "solution_steps": ["$k = 6/2 = 3$.", "$y = 3 \\times 5 = 15$."]},
    {"topic": "algebra", "subtopic": "variation", "year": 2013, "difficulty": "medium",
     "question": "$y \\propto \\frac{1}{x}$. $y = 4$ when $x = 3$. Find $y$ when $x = 6$.",
     "options": ["1", "2", "3", "4"], "answer": "2",
     "solution_steps": ["$k = yx = 12$.", "$y = 12/6 = 2$."]},
    {"topic": "algebra", "subtopic": "variation", "year": 2014, "difficulty": "hard",
     "question": "$z \\propto xy$. $z = 30$ when $x = 2$, $y = 5$. Find $z$ when $x = 3$, $y = 4$.",
     "options": ["12", "24", "36", "48"], "answer": "36",
     "solution_steps": ["$k = 30/(2\\cdot 5) = 3$.", "$z = 3\\times 3 \\times 4 = 36$."]},
    {"topic": "algebra", "subtopic": "sequences-series", "year": 2010, "difficulty": "easy",
     "question": "Find the 5th term of the AP: 1, 4, 7, …", "options": ["10", "11", "13", "16"], "answer": "13",
     "solution_steps": ["$a=1, d=3$.", "$T_5 = 1 + 4(3) = 13$."]},
    {"topic": "algebra", "subtopic": "sequences-series", "year": 2012, "difficulty": "medium",
     "question": "The first term of an AP is 2 and the common difference is 4. Find the 10th term.",
     "options": ["36", "38", "40", "42"], "answer": "38",
     "solution_steps": ["$T_{10} = 2 + 9(4) = 38$."]},
    {"topic": "algebra", "subtopic": "sequences-series", "year": 2015, "difficulty": "hard",
     "question": "Find the sum of the first 5 terms of the GP: 1, 2, 4, 8, …",
     "options": ["15", "31", "32", "62"], "answer": "31",
     "solution_steps": ["$a=1, r=2$.", "$S_5 = \\frac{1(2^5-1)}{2-1} = 31$."]},
    {"topic": "algebra", "subtopic": "inequalities", "year": 2014, "difficulty": "medium",
     "question": "Solve: $2x + 1 < 7$.", "options": ["$x < 3$", "$x > 3$", "$x \\leq 3$", "$x < 4$"], "answer": "$x < 3$",
     "solution_steps": ["$2x < 6$, $x < 3$."]},
    {"topic": "algebra", "subtopic": "inequalities", "year": 2015, "difficulty": "hard",
     "question": "Solve: $4 - x \\geq 1$.", "options": ["$x \\geq 3$", "$x \\leq 3$", "$x \\geq -3$", "$x \\leq -3$"], "answer": "$x \\leq 3$",
     "solution_steps": ["$-x \\geq -3$, flip sign: $x \\leq 3$."]},
    {"topic": "algebra", "subtopic": "linear-equations", "year": 2013, "difficulty": "hard",
     "question": "If $5(x - 1) = 3x + 7$, find $x$.", "options": ["3", "5", "6", "7"], "answer": "6",
     "solution_steps": ["$5x - 5 = 3x + 7$.", "$2x = 12$, $x = 6$."]},
    {"topic": "algebra", "subtopic": "quadratic-equations", "year": 2014, "difficulty": "easy",
     "question": "Solve: $x^2 + 5x = 0$.", "options": ["0, 5", "0, −5", "5, 5", "−5, −5"], "answer": "0, −5",
     "solution_steps": ["Factor: $x(x + 5) = 0$.", "$x = 0$ or $x = -5$."]},
    {"topic": "algebra", "subtopic": "quadratic-equations", "year": 2015, "difficulty": "medium",
     "question": "Solve: $x^2 - 4x - 5 = 0$.", "options": ["5, −1", "−5, 1", "5, 1", "−5, −1"], "answer": "5, −1",
     "solution_steps": ["Factor: $(x - 5)(x + 1) = 0$.", "$x = 5$ or $x = -1$."]},
    {"topic": "algebra", "subtopic": "indices", "year": 2010, "difficulty": "easy",
     "question": "Simplify $\\frac{2^6}{2^3}$.", "options": ["$2^2$", "$2^3$", "$2^9$", "$2^{18}$"], "answer": "$2^3$",
     "solution_steps": ["Subtract powers: $2^{6-3}=2^3$."]},
    {"topic": "algebra", "subtopic": "logarithms", "year": 2014, "difficulty": "medium",
     "question": "Solve: $\\log_5 x = 3$.", "options": ["8", "15", "25", "125"], "answer": "125",
     "solution_steps": ["$x = 5^3 = 125$."]},
    {"topic": "algebra", "subtopic": "simultaneous-equations", "year": 2015, "difficulty": "easy",
     "question": "Solve: $x = 2y$ and $x + y = 9$.", "options": ["(6, 3)", "(3, 6)", "(4, 5)", "(8, 1)"], "answer": "(6, 3)",
     "solution_steps": ["Sub: $2y + y = 9 \\Rightarrow y = 3$.", "$x = 6$."]},
    {"topic": "algebra", "subtopic": "inequalities", "year": 2011, "difficulty": "easy",
     "question": "Solve: $x - 3 > 0$.", "options": ["$x > 3$", "$x < 3$", "$x \\geq 3$", "$x \\leq 3$"], "answer": "$x > 3$",
     "solution_steps": ["Add 3: $x > 3$."]},
]
